[package]
name = "pharia"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
dotenvy = "0.15.7"
reqwest-middleware = { version = "0.4.2", features = [
    "rustls-tls",
    "json",
    "http2",
] }
reqwest-vcr = "0.3.0"
tokio = { version = "1.47.1", features = ["macros", "test-util"] }

[dependencies]
# Using native roots explicitly is desired. The default-tls assumes a Saas operation and that we
# could redeploy the containers in case we want certificates to change. Since we have a slightly
# less default on-premise buisness model, native-roots is for us.
reqwest = { version = "0.12.23", features = [
    "json",
    "rustls-tls-native-roots",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
