name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Cache our build dependencies.
      - name: Setup build cache
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test

  dependabot:
    needs: [test]
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Merge Depenabot Pull Request
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
